# Generated by Django 6.0.2 on 2026-02-26 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=255)),
                ('datum_rodenja', models.DateField()),
                ('oib', models.CharField(max_length=11)),
                ('mbo', models.CharField(max_length=50)),
                ('soba', models.CharField(max_length=50)),
                ('datum_dolaska', models.DateField()),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kontakt_obitelji', models.CharField(max_length=255)),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dom')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('upravitelj', 'Upravitelj'), ('zaposlenik', 'Zaposlenik')], max_length=20)),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=255)),
                ('pozicija', models.CharField(max_length=255)),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_ugovora', models.DateField()),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dom')),
            ],
        ),
    ]
