# Generated by Django 6.0.2 on 2026-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='upravljani_domovi',
            field=models.ManyToManyField(blank=True, related_name='upravitelji', to='dashboard.dom'),
        ),
    ]
