# Generated by Django 6.0.2 on 2026-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profil_upravljani_domovi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dom',
            options={'verbose_name': 'Dom', 'verbose_name_plural': 'Domovi'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profili'},
        ),
        migrations.AddField(
            model_name='korisnik',
            name='kontakt_obitelji_telefon',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
