# Generated by Django 6.0.2 on 2026-02-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dom_options_alter_profil_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investicija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dom')),
            ],
        ),
        migrations.CreateModel(
            name='Trosak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('kategorija', models.CharField(choices=[('kuhinja', 'Troškovi kuhinje'), ('popravci', 'Popravci u domu'), ('opcenito', 'Općeniti troškovi')], max_length=20)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dom')),
            ],
        ),
    ]
