# Generated by Django 6.0.2 on 2026-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_investicija_trosak'),
    ]

    operations = [
        migrations.AddField(
            model_name='trosak',
            name='meso',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trosak',
            name='trgovina',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
