# Generated by Django 6.0.2 on 2026-02-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_trosak_meso_trosak_trgovina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval', models.CharField(choices=[('mjesecno', 'Mjesečno'), ('kvartalno', 'Kvartalno'), ('polugodisnje', 'Polugodišnje'), ('godisnje', 'Godišnje')], default='mjesecno', max_length=20)),
                ('datum_pocetka', models.DateField()),
                ('aktivna', models.BooleanField(default=True)),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dom')),
            ],
        ),
    ]
