# Generated by Django 6.0.2 on 2026-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rezija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezija',
            name='interval',
            field=models.CharField(choices=[('bez_intervala', 'Bez intervala'), ('mjesecno', 'Mjesečno'), ('kvartalno', 'Kvartalno'), ('polugodisnje', 'Polugodišnje'), ('godisnje', 'Godišnje')], default='mjesecno', max_length=20),
        ),
    ]
