# Generated by Django 6.0.2 on 2026-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_rezija_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezija',
            name='datum_zavrsetka',
            field=models.DateField(blank=True, null=True),
        ),
    ]
