# Generated by Django 6.0.2 on 2026-02-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rezija_datum_zavrsetka'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='kapacitet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
