# Generated by Django 6.0.2 on 2026-02-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dom_kapacitet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klijent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Klijent',
                'verbose_name_plural': 'Klijenti',
            },
        ),
        migrations.AlterModelOptions(
            name='investicija',
            options={'verbose_name': 'Investicija', 'verbose_name_plural': 'Investicije'},
        ),
        migrations.AlterModelOptions(
            name='rezija',
            options={'verbose_name': 'Režija', 'verbose_name_plural': 'Režije'},
        ),
        migrations.AlterModelOptions(
            name='trosak',
            options={'verbose_name': 'Trošak', 'verbose_name_plural': 'Troškovi'},
        ),
        migrations.AddField(
            model_name='dom',
            name='klijent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.klijent'),
        ),
    ]
