# Generated by Django 6.0.2 on 2026-02-26 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_klijent_alter_investicija_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obaveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True, default='')),
                ('datum', models.DateField()),
                ('vrijeme', models.TimeField(blank=True, null=True)),
                ('zavrseno', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obaveza',
                'verbose_name_plural': 'Obaveze',
                'ordering': ['datum', 'vrijeme', 'id'],
            },
        ),
    ]
