# Generated by Django 6.0.2 on 2026-02-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_obaveza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obaveza',
        ),
    ]
