# Generated by Django 6.0.2 on 2026-02-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_delete_obaveza"),
    ]

    operations = [
        migrations.CreateModel(
            name="Smjena",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datum", models.DateField()),
                ("tip_smjene", models.CharField(choices=[("jutarnja", "Jutarnja"), ("popodnevna", "Popodnevna"), ("nocna", "Noćna"), ("slobodno", "Slobodno")], default="jutarnja", max_length=20)),
                ("zaposlenik", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="smjene", to="dashboard.zaposlenik")),
            ],
            options={
                "verbose_name": "Smjena",
                "verbose_name_plural": "Smjene",
                "ordering": ("datum", "zaposlenik__ime_prezime"),
                "unique_together": {("zaposlenik", "datum")},
            },
        ),
    ]
