# Generated by Django 6.0.2 on 2026-02-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_smjena"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="oib",
            field=models.CharField(blank=True, default="", max_length=11),
        ),
    ]
