# Generated by Django 6.0.2 on 2026-02-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_profil_oib"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="zaposlenik",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="profil", to="dashboard.zaposlenik"),
        ),
    ]
