# Generated by Django 6.0.2 on 2026-02-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_profil_zaposlenik"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profil",
            name="oib",
        ),
    ]
