# Generated by Django 6.0.2 on 2026-02-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_profil_zaposlenik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnik',
            options={'verbose_name': 'Korisnik doma', 'verbose_name_plural': 'Korisnici doma'},
        ),
    ]
