# Generated by Django 6.0.2 on 2026-02-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_korisnik_options'),
        ('dashboard', '0016_remove_profil_oib'),
    ]

    operations = [
    ]
