# Generated by Django 6.0.2 on 2026-02-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_merge_20260226_1934"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zaposlenik",
            options={"verbose_name": "Zaposlenik", "verbose_name_plural": "Zaposlenici"},
        ),
    ]
