# Generated by Django 6.0.2 on 2026-03-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_alter_zaposlenik_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="KorisnikUplata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("godina", models.PositiveIntegerField()),
                ("mjesec", models.PositiveSmallIntegerField()),
                ("iznos", models.DecimalField(decimal_places=2, max_digits=10)),
                ("datum_potvrde", models.DateTimeField(auto_now=True)),
                ("korisnik", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="uplate", to="dashboard.korisnik")),
            ],
            options={
                "verbose_name": "Uplata korisnika",
                "verbose_name_plural": "Uplate korisnika",
                "ordering": ("-godina", "-mjesec", "-datum_potvrde"),
                "unique_together": {("korisnik", "godina", "mjesec")},
            },
        ),
    ]
