# Generated by Django 6.0.2 on 2026-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_korisnikuplata"),
    ]

    operations = [
        migrations.AddField(
            model_name="korisnik",
            name="mjesecna_clanarina",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
