# Generated by Django 6.0.2 on 2026-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_korisnik_mjesecna_clanarina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='oib',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
