# Generated by Django 6.0.2 on 2026-04-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_korisnik_oib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnikuplata',
            name='datum_potvrde',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
