# Generated by Django 6.0.2 on 2026-04-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_korisnikuplata_datum_potvrde'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='klijent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.klijent', verbose_name='Organizacija'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.dom'),
        ),
    ]
